# Queno 1

In [ ]:
#lets amount of time taken for study in a day be x variable and final exam score be y variable .

In [1]:
#now lets create it in a dataframe
import pandas as pd

In [3]:
data=[[6,98],[3,80],[5,99],[8,90]]
df=pd.DataFrame(data,columns=['hours spend in a day','final exam score'])

In [4]:
df

hours spend in a day  final exam score
0                     6                98
1                     3                80
2                     5                99
3                     8                90

In [ ]:
#now we can calculate the corelation coefficient manually or by python letsdo it manually

In [ ]:
#lets calculate variable x*y 
#6*98=588
#3*80=240
#5*99=495
#8*90=720
#now add them all we get 2043

In [ ]:
#now we have to square value of x variable
#6*6=36
#3*3=9
#5*5=25
#8*8=64
#now add them all we get 134

In [ ]:
#now wehave to square value of y variable
#98*98=9604
#80*80=6400
#99*99=9801
#90*90=8100
#now add them all we get 33905 

In [ ]:
#now we can use this formulae to find pearson corelation coefficient
#formulae=no of data value*product of x and y variable-(sum of value of x variable)(sum of value of y variable)/
#sqrt [no of data value*square of x variable-square of sum of x variable][no of data value*sqaure of y variable-square of 
#sum of y variable]

In [ ]:
#now we can put the given in this formuale
#result=4*2043-22*367/sqrt [4*134-484][4*33905-134689]
#98/sqrt[52][135620-134689]
#98/sqrt[52][931]
#we get 0.44
#it is considered to be moderately corelated.


# Queno2

In [ ]:
#We can calculate spearmen corelation using scipy.stats and lets take amount of time of sleep as x variable and rating scal
#e as y variable.

In [1]:
x=[5,8,4,3,6,1]
#amount of hours of sleep in x variable
y=[3,7,5,4,7,2]
#rating scale given by each individual in y variable

In [2]:
from scipy.stats import spearmanr

In [3]:
spearmanr(x,y)

SignificanceResult(statistic=0.8116794499134279, pvalue=0.04985758510134035)

In [ ]:
#so with thehelp of scipy function we got the result of spearmen rank corelation is 0.811.

In [ ]:
#SO as the value of spearman corelation is 0.811 which proves that both variable x and y have strong monotonic increasing
#relationship.

# Queno 3

In [ ]:
#here in this case also take two variable xand y x variable as hours spent in excercise per week and y variable as 
#as bmi of individual spending timwe in exercise.

In [4]:
import numpy as np

In [6]:
x=np.linspace(14,18,num=50)
x
#so this is the hours spent in a week fro 14 to 18 of 50 person in x variable.

array([14.        , 14.08163265, 14.16326531, 14.24489796, 14.32653061,
       14.40816327, 14.48979592, 14.57142857, 14.65306122, 14.73469388,
       14.81632653, 14.89795918, 14.97959184, 15.06122449, 15.14285714,
       15.2244898 , 15.30612245, 15.3877551 , 15.46938776, 15.55102041,
       15.63265306, 15.71428571, 15.79591837, 15.87755102, 15.95918367,
       16.04081633, 16.12244898, 16.20408163, 16.28571429, 16.36734694,
       16.44897959, 16.53061224, 16.6122449 , 16.69387755, 16.7755102 ,
       16.85714286, 16.93877551, 17.02040816, 17.10204082, 17.18367347,
       17.26530612, 17.34693878, 17.42857143, 17.51020408, 17.59183673,
       17.67346939, 17.75510204, 17.83673469, 17.91836735, 18.        ])

In [7]:
y=np.linspace(18,24,num=50)

In [8]:
y
#so this isthe bmi of 50 individual doing exercise.

array([18.        , 18.12244898, 18.24489796, 18.36734694, 18.48979592,
       18.6122449 , 18.73469388, 18.85714286, 18.97959184, 19.10204082,
       19.2244898 , 19.34693878, 19.46938776, 19.59183673, 19.71428571,
       19.83673469, 19.95918367, 20.08163265, 20.20408163, 20.32653061,
       20.44897959, 20.57142857, 20.69387755, 20.81632653, 20.93877551,
       21.06122449, 21.18367347, 21.30612245, 21.42857143, 21.55102041,
       21.67346939, 21.79591837, 21.91836735, 22.04081633, 22.16326531,
       22.28571429, 22.40816327, 22.53061224, 22.65306122, 22.7755102 ,
       22.89795918, 23.02040816, 23.14285714, 23.26530612, 23.3877551 ,
       23.51020408, 23.63265306, 23.75510204, 23.87755102, 24.        ])

In [10]:
#so first of all calculate covariance of x and y 
from numpy import cov
covariance_of_x_and_y=cov(x,y)

In [11]:
covariance_of_x_and_y

array([[1.41607663, 2.12411495],
       [2.12411495, 3.18617243]])

In [ ]:
#so the cov of x and y is 2.12 and now we have to calculate stasndard deviation of x and y.

In [13]:
import statistics
statistics.stdev(x)
#so standard deviation of x variable is 1.18

1.18999018262149

In [14]:
statistics.stdev(y)
#standard deviation of y variable is 1`.78

1.7849852739322347

In [16]:
#now we can multiply standard deviation of x and y
result=1.18*1.78
result
#so we got the result that is 2.10

2.1004

In [18]:
#so for pearson corelation we have to do cov(x,y)/std(x*std(y))
pearson_core=2.12/2.10
pearson_core
#so here value is 1.00 whichs total positive corelation.

1.0095238095238095

In [ ]:
#so here we got the result 1.00 as pearson corelation coefficient orwe can also calculate it using scipy library

In [19]:
#now for calculating spearman rank corelation
spearmanr(x,y)
#so we got spearman rank corelation value that is 0.99 which showsstrong increasing monotonic relationship.

SignificanceResult(statistic=0.9999999999999999, pvalue=0.0)

# Queno 4

In [ ]:
#same here we have to take x and y as vasriable x as no of hours spend in watching tv and y as their level of physical
#activity

In [20]:
x=np.linspace(5,8,50)

In [21]:
x 
#so here no of hours spent by in 50 individuals in a day 

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [24]:
y=np.linspace(8,1,50)

In [25]:
y
#so this is their level of physical activity from 8 to 1.

array([8.        , 7.85714286, 7.71428571, 7.57142857, 7.42857143,
       7.28571429, 7.14285714, 7.        , 6.85714286, 6.71428571,
       6.57142857, 6.42857143, 6.28571429, 6.14285714, 6.        ,
       5.85714286, 5.71428571, 5.57142857, 5.42857143, 5.28571429,
       5.14285714, 5.        , 4.85714286, 4.71428571, 4.57142857,
       4.42857143, 4.28571429, 4.14285714, 4.        , 3.85714286,
       3.71428571, 3.57142857, 3.42857143, 3.28571429, 3.14285714,
       3.        , 2.85714286, 2.71428571, 2.57142857, 2.42857143,
       2.28571429, 2.14285714, 2.        , 1.85714286, 1.71428571,
       1.57142857, 1.42857143, 1.28571429, 1.14285714, 1.        ])

In [26]:
#now for finding pearson corelation we have
from scipy.stats import pearsonr

In [27]:
pearsonr(x,y)

PearsonRResult(statistic=-1.0, pvalue=0.0)

In [ ]:
#so here value of pearson corelation is -1 which shows which shows total negative linear corelation.

# Queno 5

In [ ]:
#this data shows coke softdrink is most preferred among adults.

In [ ]:
#while pepsi is prefereble to middle aged and adult both.

In [ ]:
#Another softdrink that is mountain dew is not popular among adults but it is preferable by middleaged people.

# Queno 6

In [ ]:
#consider two variables x and y and x as no of sale calls made per day while y as no of sales made per week.

In [31]:
x=np.linspace(50,60,30)

In [32]:
x

array([50.        , 50.34482759, 50.68965517, 51.03448276, 51.37931034,
       51.72413793, 52.06896552, 52.4137931 , 52.75862069, 53.10344828,
       53.44827586, 53.79310345, 54.13793103, 54.48275862, 54.82758621,
       55.17241379, 55.51724138, 55.86206897, 56.20689655, 56.55172414,
       56.89655172, 57.24137931, 57.5862069 , 57.93103448, 58.27586207,
       58.62068966, 58.96551724, 59.31034483, 59.65517241, 60.        ])

In [34]:
x1=np.round(x,decimals=-1)
x1 
#so here we got no of sales call per day of 30 repreesentatives in x1 variable.

array([50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
       50., 50., 60., 60., 60., 60., 60., 60., 60., 60., 60., 60., 60.,
       60., 60., 60., 60.])

In [36]:
y=np.linspace(40,55,30)
y

array([40.        , 40.51724138, 41.03448276, 41.55172414, 42.06896552,
       42.5862069 , 43.10344828, 43.62068966, 44.13793103, 44.65517241,
       45.17241379, 45.68965517, 46.20689655, 46.72413793, 47.24137931,
       47.75862069, 48.27586207, 48.79310345, 49.31034483, 49.82758621,
       50.34482759, 50.86206897, 51.37931034, 51.89655172, 52.4137931 ,
       52.93103448, 53.44827586, 53.96551724, 54.48275862, 55.        ])

In [38]:
y1=np.round(y,decimals=-1)
y1
#so this is amount of sales per week of 30 representatives in y variable.

array([40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 50., 50., 50.,
       50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
       50., 50., 50., 60.])

In [40]:
#now we calculate using scipy
pearsonr(x1,y1)

PearsonRResult(statistic=0.6970966755769258, pvalue=1.8668833881048666e-05)

In [ ]:
#so here value of pearson corelation is 0.69 which shows both variable is strongly corelated.