# Que no 1

# Difference between Z test and T test

In [ ]:
#Z test is the statistical test used to analyse whether two population means are different or not when the variances are
# known, and the sample size is large.

In [ ]:
#While t test is a parametric test used to identify mean of two datasets difference when variance is not known.

In [ ]:
#Z test is used in large sample.

In [ ]:
#While t test is used in small sample.

In [ ]:
#Sample size in z test should not be less than 30.

In [ ]:
#While sample size in t test should be less than 30.

In [ ]:
#Use of z test with an example;
#let;s consider mean height of student in class is more than 170cm with a standard deviation of 10.
#Now if sample of 50 students is selected with a mean height of 175cm.
#First of all calculate z value and significance level would be used 0.05.

In [ ]:
#So here sample size =50 and it is a case of right-tailed one-sample z test and calculate z value
# z value=(sample mean-population mean/population std/squareroot sample size)
#so after applying this formuale we get z value that is 3.54.
#So the from z table critical valueat alpha 0.05 is 1.645 which is less than z value 3.54 and there is acceptance of 
#alternate hypothesis.
#So we can conclude that mean of height of student is greater than 170 cm.


In [ ]:
#Use of t test with example;
#A store want to improve its sale
#His previous sale shows data of 30 salesman of average 40 rs sale.
#Aftersome training sale improves with 60rs average sale with standard deviation of 20 rs.
#Now we have to calculate to predict did training improves sale.
#Now we have to calculate t value and critical value
#So we get t value 5.47 and critical value at alpha 0.05 is 1.711
#So there is acceptance of alternatehypotheses as t value> critical value.
#And now we can conclude that training improve sale in store. 

# Que no 2

# Difference between one nailed and two nailed test

In [ ]:
#One tailed hypotheses test are known as one-sided tests because we can test for result in only one direction.

In [ ]:
#While two-tailed hypotheses tests are also known as two sided tests because we can test for effect in both directions.

In [ ]:
#In one-tailed test we use an alpha of 5% and each distribution has one shaded region of 5%.

In [ ]:
#While in two tailed tests we use an alpha of 5% and distribution has two shaded regions of 2.5%*2=5%.

In [ ]:
#In one tailed test alternate hypotheses is mean difference is greater than 0 and in null hypotheses mean difference
# is equal or less than 0.

In [ ]:
#In two tailed test in null hypotheses the result equals 0 and in alternate hypotheses the result is not equal to 0. 

# Que no 3 Type 1 error and Type 2 error

In [ ]:
#Type 1 error is acceptance of alternate and rejection of null hypotheses that is actually false positive result.

In [ ]:
#While type 2 error is acceptance of null hypotheses that is actually false negative result. 

In [ ]:
#In type 1 error p value is lower than significant value which means our result is consistent with alternative hyopotheses.

In [ ]:
#While in type 2 error p value is higher than significant value means our result is considered non-significant is 
# consistent with null hypotheses. 

In [ ]:
#Type 1 error example;After various discoveries we found tiger is endangered but we didn't consider it as endangered.
#In this there is acceptance of alternate hypotheses where tiger is not endangered but after various discoveries we 
#found it endangered.

In [ ]:
#Type 2 error example;A guilty person is not convicted so in this case there is failure to reject null hypotheses that is 
#actually false.

# Queno 4 and 6

# Bayes theorem

In [ ]:
# Bayes theorem describes probability of occurence of event for given condition.

In [ ]:
#Formula for bayes theorem are;
#P(A/B)=P(A).P(B/A)/P(B)
#P(A)=probability of A occuring
#P(B)=probability of B occuring
#P(A/B)=probability of A given B.
#P(B/A)=probability of B given A.

In [ ]:
#Example of bayes theorem;
#Let there are two bags that is A and B
#Bag A contains 4 white and 6 black balls.
#Bag B contains 4 white and 3 black balls.
#Now one ball is drawn random at one bags and it is found to be black, what is probability that it was drawn from bagA. 

In [8]:
#so now lets calculate;
#PE1==1/2
#PE2==1/2
#E1 be the event of choosing bag A and E2 be the event of choosing bag B is equal to 1/2 as it is about only
#bag A.
#P(A/E1)==6/10 
#A be the event of drawing black ball from bag A.
#P(A/E2)==3/7 
#A be the event of drawing black ball from bag B.
#P(E1/A)==PE1*P(A/E1)/PE1*P(A/E1)+P(E2)*P(A/E2)
#So after calculating we got result 7/12
#so by using ba



# Queno 5.Confidence Interval

In [ ]:
#Confidence interval in statistics refers to the probability that a population parameter will fall between estimated set
# of values.

In [ ]:
#For example if a point estimate is generated from statistical model of 20 then with 95% confidence interval of 18 to 22
# then it can be inferred that 95% probbaility that true value falls within that range.

In [ ]:
#Confidence intervals measure the degree of uncertainity or certainity in a sampling method.

In [ ]:
#We can take any number of probability limits,with most common being 95% or 99% confidence level.

In [ ]:
#For example; Suppose we get a sample of 50 people in states with their average age 35.

In [ ]:
#Now we can estimate mean of age large number of population in state. 

In [ ]:
#If we take 95% confidence interval and suppose we get estimated mean from 33 to 37 by calculating margin of error.

In [ ]:
#Then we can conclude with 95% probablity that estimated mean falls with in range of 33 to 37.

# Queno 7

In [ ]:
#so here we get confidence interval of 95% so z critical value at 95% is 1.96.

In [ ]:
#mean of sample is 50 and standard deviation is 5. 

In [ ]:
#so now we have to calculate standard of error(sor).

In [ ]:
#So here sample size is not give so we cannot calculate standard of error.

In [ ]:
#so now we can take sample size of 50 which is more than 30 and for this we have to use z value which is 1.96.

In [ ]:
#sor=5/sqrt sample size
#we get sor=0.70

In [1]:
#now calculate margin of error(mor)
mor=0.70*1.96
mor

1.3719999999999999

In [2]:
mean=50
#we have to calculate estimated mean
lower=mean-mor
lower

48.628

In [3]:
upper=mean+mor
upper

51.372

In [ ]:
#so we conclude with 95% confidence level that estimated mean would be between 48.62 to 51.37.

# Que no 8

# Margin of Error

In [ ]:
#Margin of error is a range of values above and below the actual results from survey.

In [ ]:
#For example if we have to estimate mean of population from given sample mean 50 and we got 3% as margin of error.
#Then we can conclude that mean of real population is between 47% and 53% with 3% of margin of error. 

In [ ]:
#In case of Margin of error as sample size increases the margin of error decreases.
#lets see it with an example of mean estimation of both samplesize of 20 and samplesize of 100 with 95% confidence interval.

In [ ]:
sample_size=20
mean=50
standard_deviation=5
standard_error=5/sqrt20=1.11
critical_zvalue=1.96 #critical z value is 1.96 for 95% confidence_level.
margin of error=2.17

In [ ]:
sample_size=100
mean=50
standard_deviation=5
standard_error=5/sqrt100=0.5
crtical_zvalue=1.96 #critical_zvalue for 95% confidence_level
margin of error=0.98 
#so we see that sample with larger size has less margin of error and sample with smaller size has large margin of error.

# Queno 9

# Z score

In [ ]:
#Formulae for z score is;
#z=z-score
#x=the value being evaluated
#m=mean
#s=standard deviation
#z=(x-m)/s

In [2]:
x=75
m=70
s=5
z=(x-m)/s
z

1.0

In [ ]:
#So in this case z score is 1 which is positive because the value lies above the mean.

# Que no 10

In [1]:
#So for this we have to generate sample of given mean and standarddeviation;
import numpy as np
#mean=loc
#scale=standarddeviation
#size=sample size
samplewl=np.random.normal(loc=6,scale=2.5,size=50)
samplewl

array([ 5.4577775 ,  4.60115864,  6.3152263 , 10.57151272,  6.74313996,
        2.19472768, 12.24775089,  7.67695213,  6.93747093,  1.20339195,
        7.42378302,  3.98801845,  3.7071356 ,  4.21973732,  5.65558925,
        9.17791563, 11.59636743,  6.06287954,  3.08314933,  6.64860027,
        3.86113839, 11.39933872,  6.25317828,  7.99600507,  5.1199882 ,
        5.63299435,  7.95427683,  5.09821715,  5.59320563,  8.90226468,
        0.91885639,  5.03412191,  2.06507877,  9.00426971,  4.16957193,
        6.90970189,  4.9975278 , 10.93457679,  4.82899012,  7.71386225,
        7.57343337,  5.17203924,  9.39679236, 10.3431696 ,  9.36354909,
        8.57338936,  3.59295355,  6.6312191 ,  9.16327845,  7.5416366 ])

In [ ]:
#now we have to conduct one sample t test for determining p value.

In [7]:
import scipy.stats as stats
t_statistic,p_value=stats.ttest_1samp(a=samplewl,popmean=6)

In [6]:
t_statistic

-0.7818423101942854

In [7]:
p_value

0.43806897603908623

In [ ]:
#so here we get p value 0.438 which is greater than alpha that is 0.05 so here is rejection of alternate hypotheses and 
#acceptance of null hypotheses.

In [ ]:
#So we can conclude that after observation the expected mean of sample is equal to the specified mean of sample that is 6.

# Queno 11

In [11]:
#Calculate number of people satisfied with their job 
#no_of_people=65% that is sample mean is 0.65
#confidence_level=95%=0.95
#alpha=1-confidence_level=0.05=5%

In [ ]:
#so the standard critical value at 95% confidence level in normal distribution table is 1.96

In [ ]:
#lowerlimit=mean of sample - standard critical value sqrt mean of sample*(1-mean of sample)/sample size

In [ ]:
#so in this way lower limit=0.65-1.96 sqrt 0.65*(1-0.65)/500
#we got answer 0.648
#that is 64.8%.

In [ ]:
#now upper limit=mean of sample + standard critical value sqrt mean of sample*(1-mean of sample)/sample size

In [ ]:
#so in this way upper limit=0.65+1.96 sqrt 0.65*(1-0.65)/500
#we got answer 0.651.
#that is 65.1

In [ ]:
#So we can conclude that between 64.8% to 65.1% people aresatisfied with 95% confidence level.

# Queno 12

In [2]:
#This is a case of two sample t test
#Lets createtwo sample sampleA and sampleB and sample size should be less than 30 as it would be appropriate for t test.
sampleA=np.random.normal(loc=85,scale=6,size=29)#loc is mean and scale is standard deviation
sampleA

array([88.55363594, 81.85374614, 84.05455485, 89.06192535, 82.83091548,
       77.93614074, 98.158198  , 89.01000554, 76.88300036, 83.08475872,
       79.2572832 , 80.89789007, 88.75454009, 80.90079218, 87.18843032,
       81.70978678, 85.13311079, 92.13999647, 94.17364193, 70.57418378,
       75.00057131, 87.83161392, 78.59073819, 79.85131319, 85.39558103,
       85.75743895, 84.89980034, 81.35834947, 99.0650608 ])

In [3]:
sampleB=np.random.normal(loc=82,scale=5,size=29)
sampleB

array([73.95392478, 87.74567688, 82.13869933, 86.87518722, 81.97571122,
       84.30558469, 81.71563966, 80.08089654, 80.10814466, 84.56011567,
       78.31192818, 80.56065891, 78.2746176 , 85.12101481, 78.43616113,
       85.47400232, 86.79874007, 77.30290684, 72.05336966, 74.35241183,
       77.94923989, 76.26033924, 87.00386608, 71.78176964, 86.93218922,
       74.44362483, 80.55815573, 87.25586958, 84.95734491])

In [4]:
#so for this we have to import some library
from statsmodels.stats.weightstats import ttest_ind
import pingouin as pg

In [5]:
result=pg.ttest(sampleA,sampleB,correction=True)
result

T        dof alternative     p-val         CI95%   cohen-d  \
T-test  2.346942  52.186955   two-sided  0.022758  [0.51, 6.56]  0.616337   

         BF10    power  
T-test  2.522  0.63556

In [ ]:
#so here we got p value 0.02 which is greater than alpha that is 0.01 which implies that mean score of student in sampleA
# is statistically not different from mean score of sampleB and it is a null hypotheses.

# Que no 13

In [ ]:
#Calculating 90percent confidence level of population mean from given sample.
#sample mean=65
#confidence level=0.90=90%
#alpha=0.10=10%

In [ ]:
#now we have to calculate lower limit and upper limit
#so standard critical value at 90% confidence lvel is 1.645.

In [ ]:
#lowerlimit=mean of sample - standard critical value *standard deviation/sqrtsamplesize

In [ ]:
#lowerlimit=65-1.645*8/sqrt50
#63.1

In [ ]:
#upper limit=mean of sample - standard critical value *standard deviation/sqrtsamplesize


In [ ]:
#upper limit=65+1.645*8/sqrt50
#66.86

In [ ]:
#Hence the true population mean at 90% confidence interval is between 63.1 and 66.86. 

# Queno 14

In [6]:
#First of all create a sample of reaction time
samplert=np.random.normal(loc=0.25,scale=0.05,size=30)
samplert

array([0.20267187, 0.19377541, 0.25363808, 0.19819436, 0.20323779,
       0.28999822, 0.24146194, 0.21846933, 0.21604436, 0.17158404,
       0.17506957, 0.21208574, 0.22843891, 0.21229065, 0.23734964,
       0.20373049, 0.31077386, 0.16982222, 0.23897889, 0.25385688,
       0.26430232, 0.25208314, 0.30873768, 0.19966039, 0.22566998,
       0.20597547, 0.22617149, 0.25482181, 0.22007637, 0.22298073])

In [ ]:
#now we can use one sample t test with use of python

In [8]:
t_statistic,p_value=stats.ttest_1samp(a=samplert,popmean=0.25)

In [9]:
t_statistic

-3.5210906891289873

In [10]:
p_value

0.0014421683566927584

In [ ]:
#alpha=1-confidence level=1-0.90=0.10 ,that is 10% which is greater than p value and there is rejection of null hypotheses
#in favour of alternate hypothesis.

In [ ]:
#so we can conclude that mean of sample is not equal to 0.25 so caffein may have signigicant effect or not 
#on reaction time at 90% confidence level.