In [1]:
#queno1
import numpy as np

In [2]:
list=['1','2','3','4','5']
type(list)



#the data type of this variable is list.


list

In [3]:
array_list=np.array(object=list)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
type(array_list)

#data type of this array_list is numpy.ndarray

numpy.ndarray

In [6]:
dt=np.dtype('<U1')
print("byte order is :",dt.byteorder)
print("size is:",dt.itemsize)
print("datatype is:",dt.name)

#this is the data type and details of the np.dtype(''<U1') which is subtype of datatype numpy.ndararay.

byte order is : =
size is: 4
datatype is: str32


In [ ]:
#so this the difference between two variables first one which datatype is list has become the object of arraylist darray


In [7]:
#queno2
list

['1', '2', '3', '4', '5']

In [8]:
type(list[0]),type(list[1]),type(list[2]),type(list[3]),type(list[4])

(str, str, str, str, str)

In [ ]:
#by using indexing we are able to know the element datatype of list.

In [9]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [10]:
type(array_list[0]),type(array_list[1]),type(array_list[2]),type(array_list[4])

(numpy.str_, numpy.str_, numpy.str_, numpy.str_)

In [ ]:
#so in this way data type of element in array_list is numpystring.

In [ ]:
#queno3

In [11]:
list=[1,2,3,4,5]

In [12]:
array_list=np.array(object=list,dtype=int)

In [13]:
array_list

array([1, 2, 3, 4, 5])

In [14]:
type(list),type(array_list)

(list, numpy.ndarray)

In [ ]:
#data type of list is same but datatype of array_list has changed from numpy.str to numpy.ndarray.

In [15]:
type(list[0]),type(list[1]),type(list[2]),type(list[3]),type(list[4])

(int, int, int, int, int)

In [16]:
type(array_list[0]),type(array_list[1]),type(array_list[2]),type(array_list[4])

(numpy.int32, numpy.int32, numpy.int32, numpy.int32)

In [ ]:
#so these are the data type of list and array_list which has changed from numpy.str to numpy.int32

# queno4

In [3]:
import numpy as np
num_list=[[1,2,3],[4,5,6]]

In [4]:
num_array=np.array(object=num_list)

In [5]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr=num_array

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(arr.shape)

(2, 3)


In [9]:
print(arr.size)

6


In [ ]:
#so in this way shape of num_array is (2,3) and size is 6.

# queno 5 

In [14]:
zero_matrix=np.zeros((3,3))

In [15]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
zero_matrix.size,zero_matrix.shape

(9, (3, 3))

In [ ]:
#so in this way we are able to create matrix of 3*3 containing zero and having required shape and size.

# queno 6

In [24]:
zero_matrix=np.zeros((5,5))

In [25]:
zero_matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
zero_matrix=np.diag([1,1,1,1,1])

In [27]:
zero_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
#so in this way we are able to convert zero_matrix containing zero to matrix containing 1 as diagonally and rest as 0.