# Queno 1

# Probability Mass Function

In [ ]:
#Probability mass function is used for discrete random variable.

In [ ]:
#It is evaluated at an exact point.

In [ ]:
#The formulae for probability mass function is f(x)=P(X=x).

In [ ]:
#To determine the cumulative distribution frequency,the probability mass function needs to be summed up to x values.

In [ ]:
#Example of Probability mass function is;suppose a coin is tossed twice and sample space recorded as S=[HH,HT,TH,TT].

In [ ]:
#Now the probability of getting head needs to be determined that is X be the random variable that shows how many heads obtained.

In [ ]:
#X can take on values 0,1,2 the probability that X will be equal to 1 is 0.5 or the probability mass function of X evaluated at 1 will be 0.5.

# Probability Density function

In [ ]:
#It is used for continous random variable.

In [ ]:
#It is evaluated between a range of values.

In [ ]:
#The formulae for probability density function is given as p(X)=dF(x)/dx=F'(x),where F(x) is cumulative distribution function. 

In [ ]:
#To determine cumulative distribution frequency the probabaility density function needs to be integrated from -infinity to x.

In [ ]:
#Now let us consider an example with PDF,f(x)=x+3,when 1< x < = 3.now we have to find P(2<X<3).

In [ ]:
#Now integrating x+3 within the limits 2 and 3 gives answer 5.5.

# Queno 2

# Cumulative Density Function

In [ ]:
#Cumulative distribution function is used to describe the probability distribution of random variables.

In [ ]:
#It can be used to describe probability of discrete,continous or mixed variable.

In [ ]:
#The cumulative density function of random variable to be calculated at point x is represented as Fx(X).

In [ ]:
#Where X is probability that takes a value less than or equal to x and that lies in semi-closed interval(a,b],where a<b in case of discrete variable.

In [ ]:
#Now with simple example we know the probability of getting an outcome by rolling a six-sided die is given as;
#probability of getting 1=p(X<_1)=1/6
#probability of getting 2=p(X<_2)=2/6
#probability of getting 3=P(X<_3)=3/6
#probability of getting 4=P(X<_4)=4/6
#probability of getting 5=P(X<_5)=5/6
#probability of getting 6=P(X<_6)=6/6=1
#So in this way it is proved that probability value always lies between 0 and 1 and it is non-decreasing and right continous in nature.

# Queno 3

In [ ]:
#Some examples of situation where normal distribution is used as a model are;
#1.Measuring blood pressure
#Normal distribution data used as blood pressure reading of model person in general that is 100-130 diastolic and 60-80 sys.
#2.Height of the people
#Most of the people in a specificpopulation are of average height as very small number of people are extremely short or extremely small.
#therefore it follows normal distribution.

In [ ]:
#so with the in python we will see how parameter change affect shape and size of normal distribution. 

In [1]:
from scipy import stats
#first of all import stats from scipy

In [4]:
#now take parameters mean=30,standard deviation=5
mean=30
standard_deviation=5
data=stats.norm(loc=mean,scale=standard_deviation)


In [6]:
#now create sample
sample=data.rvs(size=20)
sample

array([32.73714688, 26.61974739, 29.73931631, 30.98549636, 26.4911322 ,
       32.160677  , 32.8741378 , 17.88580498, 37.01956152, 30.96536195,
       35.23830071, 31.76933483, 33.60201816, 34.26948905, 33.71552619,
       23.71673208, 30.45841819, 38.0526446 , 35.62049535, 33.57501705])

In [7]:
# in the same way after changing parameter
mean=50
standard_deviation=8
data=stats.norm(loc=mean,scale=standard_deviation)

In [9]:
sample=data.rvs(size=20)
sample

array([49.05029309, 57.32545622, 51.43575258, 48.13406314, 51.80178194,
       36.92157612, 54.25304556, 58.30302521, 42.79274806, 48.56418349,
       49.18581987, 48.12763864, 61.23955259, 61.42411097, 42.84097997,
       50.15452533, 51.58344156, 57.57877635, 34.02925925, 58.31217534])

In [ ]:
#so in this way we can see change in the shape of sample after changing parameter that is mean and standard deviation.

# Queno 4

# Importance of Normal Distribution

In [ ]:
#The normal distribution is symmetric and has a skewness of zero.

In [ ]:
#The skewness measures the symmetry of a distribution with respect to normal distribution.

In [ ]:
#Normal distribution is an important probability distribution in math and statistics because many continous data in nature
#and psychology display this bell-shaped curve when compiled and graphed.

In [ ]:
#Normal distribution is widely used in financing industries to examine price action of stocks and to account for returns in asset class.

# Que no 5

# Bernauli Distribution

In [ ]:
#Bernauli distribution is a discrete probability distribution,meaning it's concerned with discrete random variables.

In [ ]:
#A discrete random variable is one that has finite or countable number of possible values.

In [ ]:
#Bernouli distribution applies to events that have one trial and two possible outcomes.
#for example will student ramesh pass or fail in math test.

In [ ]:
#So whenever we have an event that has only two possible outcomes,Bernouli distribution enables us to calculate probability of each outcome.

# Difference between Berenouli and Binomial distribution

In [ ]:
#Bernouli distribution is a type of binomoal distribution.

In [ ]:
#Bernouli distribution applies to events that have one trial and two possible outcomes.

In [ ]:
#But when we have more han one trial for ex when we flip coin five times -the binomial distribution gives discrete
#probability distribution of the no of 'successes' or 'failures'

# Queno 6

In [ ]:
#Create dataset of normal distribution with the help of python of mean=50 and standard deviation=10.

In [3]:
#first of all import numpy
import numpy as np
Mean=50
Standard_deviation=10
size=31
dataset=np.random.normal(Mean,Standard_deviation,size)
dataset

array([41.34399649, 45.46764715, 41.09314937, 39.17726939, 45.38206046,
       49.86393017, 34.1356605 , 70.15908328, 51.13318347, 31.00646894,
       55.09490967, 50.20262801, 32.55117018, 51.88872123, 55.77975558,
       45.41994154, 46.18663258, 49.71239237, 63.17213294, 64.1688634 ,
       59.85866472, 47.2975606 , 41.89790247, 57.38556366, 59.79277913,
       54.89262678, 41.66330882, 42.72963127, 35.50171703, 35.53071302,
       53.56951266])

In [ ]:
#The probability of getting more than 60 in a dataset is very low only two times in 31 observation.

In [ ]:
#Now another method is to find it by using z score

In [ ]:
#so we have to convert 60 in to z score or standard score by subtracting mean 50 from 60 we get 10 and then divide by standard
#deviation 10 with 10 we get 1 as z score and its value 0.8413.

In [ ]:
#The probability of score above 60 is very less in this case as it would be in the far right tail of the distribution.

# Queno 7

# Uniform Distribution

In [ ]:
#Uniform distribution is a term in statistics used to describe a form of probability distribution where every possible
#outcome has an equal likelihood of happening.

In [ ]:
#The probability is constant since each variable has equal chances of being the outcome.

In [ ]:
#For example if we stand on a street corner and start to randomly hand pamphlet then every passerby have an equal chances
# of being given the pamphlet.The percentage of probability is 1 divided by total no of outcomes.

# Queno 8

# Z-Score and Its importance

In [ ]:
#Z score or standard score is very useful statistic because it allows us to calculate probability of score occuring within 
# our normal distribution dataset.

In [ ]:
# It's calculation process as we have seen in queno 6.

In [ ]:
#Z score indicates the position of data values by measuring their distance from mean.

In [ ]:
#Z score gives an idea of where data points fit into the distribution.

In [ ]:
#It is also used to compare two different distributions.

In [ ]:
#Z score is also used in hypothesis testing.

# Que no 9

# Central Limit Theorem

In [ ]:
#The central limit theorem relies on concept of a sampling distribution,which is probability distribution of statistic for
# a large number of samples taken from population.

In [ ]:
#Suppose we draw a random sample from a population and calculate a statistic for the sample such as mean.

In [ ]:
#Now we draw another random sample of same size,and again calculate the mean.

In [ ]:
#We repeat this process many times,and end up with large number of means,one for each sample.

In [ ]:
#According to central limit theorem if we take large samples from population,the sample means will be normally distributed
#even if population is not normally distributed.

In [ ]:
#For example;if we take 1000 samples from population each with sample size of 40.
#The sample means follow normal distribution, as predicted by central limit theorem.

In [ ]:
#In central limit theorem sampling size should be large that is more than 30 or equal to 30.

# Que no 10

# Assumptions of Central limit Theorem

In [ ]:
#Data must be randomly sampled one by one in different sample group.

In [ ]:
#Every sample should be unrelated to one another means they should not impact one another.

In [ ]:
#Also overall sample size after combining every sample should not exceed 10% of population.

In [ ]:
#Also every sample of size 30 is considered reasonable.