# Que no 1

# Assumptions Required in One Way ANOVA

In [ ]:
#Each sample would be drawn from normally distributed population and should be same in size.

In [ ]:
#The variances of populations that the samples come from are equal.

In [ ]:
#The observations in each are independent of each other and observations within group obtained by random sample. 

In [ ]:
#If these assumptions are not met then results of our one way ANOVA could be unreliable. 

# Two Way ANOVA Assumptions

In [ ]:
#In two way ANOVA two variables for testing should be independent of each other.

In [ ]:
#One variable should not affect the other variables.

In [ ]:
#In two way ANOVA variation around mean for each set of data should not vary significantly for all groups. 

In [ ]:
#The two variables in two way ANOVA test should have a normal distribution.

In [ ]:
#Suppose we took three different brands of chocolate of Munch,Diary Milk and Fivestar. 

In [ ]:
#We take six sample from Munch and Diary milk and 5 sample from Fivestar.

In [ ]:
#So in this case sample size were different so there would be violation of the validity of reult in testing ANOVA in 
#these category of chocolates.

# Que no 2

In [ ]:
#The three types of using ANOVA are one-way ANOVA,two-way ANOVA and n-way ANOVA.

In [ ]:
#We use one way ANOVA when we have to collect data about one independent variable and one quantative dependent variable
#and independent variable have at least three or more categories.

In [ ]:
#It is a hypotheses test which allows to compares between the means of three or more groups of data of one independent 
#variable.

In [ ]:
#We use two way ANOVA when we have to collect data of two independent or factor variable and we can compare multiple groups
#of two independent variable that howit affect dependent variable.

In [ ]:
#When use n way ANOVA when researcher wants to compare multiple groups of independent variable more than two that may 
#3,4 or else.

# Queno 3

In [ ]:
#Variance partitioning is also called partition of total sum of squares in ANOVA. 

In [ ]:
#There are three types partioning of sum of sqaures in ANOVA.

In [ ]:
#First one is partition of sum of squares due to groups which measures variance difference between groups. 
#The between partition is measure of variability across means,which will be part of numerator F statistic.

In [ ]:
#Second one is partition of sum of square for error which measures random variation within group. 
#The within partition is a mmeasure of variability within each level and will contribute to denominator of F statistic.

In [ ]:
#The third one partition of sum of squares total that is sum of squared deviation from mean is called sum of square total.
#It can be calculated by subtracting mean from all data point square their difference and add them together or it can also
#simply calculated by the sum of square within output with sum of square between output.

# Que no 4

In [2]:
import pandas as pd

In [36]:
data=[[1,76,1],[2,86,1],[3,78,1],[4,90,2],[5,87,2],
      [6,86,2],[7,65,3],[8,90,3],[9,99,3]]

In [37]:
df=pd.DataFrame(data,columns=['subject','score','faculty'])

In [38]:
df

subject  score  faculty
0        1     76        1
1        2     86        1
2        3     78        1
3        4     90        2
4        5     87        2
5        6     86        2
6        7     65        3
7        8     90        3
8        9     99        3

In [ ]:
#For calculating sum of square total we have calculate faculty wise mean.
#FACULTY 1 AS social science
#faculty 2 as science
#faculty 3 as arts

In [9]:
faculty_socialscience_mean=(76+86+78)/3
faculty_socialscience_mean

80.0

In [10]:
faculty_science_mean=(90+87+86)/3
faculty_science_mean

87.66666666666667

In [11]:
faculty_arts_mean=(65+90+99)/3
faculty_arts_mean

84.66666666666667

In [12]:
#Now calculate whole mean of score=
grand_mean=(76+86+78+90+87+86+65+90+99)/9
grand_mean

84.11111111111111

In [ ]:
#Now square all the score and add all

In [13]:
square_score=(76*76)+(86*86)+(78*78)+(90*90)+(87*87)+(86*86)+(65*65)+(90*90)+(99*99)
square_score

64447

In [ ]:
#Now we have to squareeach faculty mean and multiply it with number of subject and add them later

In [19]:
result=3*80*80+3*87.66*87.66+3*84.66*84.66
result

63754.77359999999

In [21]:
#now we have to square the grandmean and multiply it with 9
result2=84.11*84.11*9
result2

63670.4289

In [22]:
#Now we have to find sum of square within faculty and between faculty
#sum_of_squarewithin=sum of all squarescore -sum of square of all faculty mean multiply by no of subject of each faculty.
sum_of_squarewithin=64447-63754.7
sum_of_squarewithin

692.3000000000029

In [25]:
#Now we have to calculate sum of squares between
#sum of squaresbetween=sum of square of all faculty mean multiply by no of subject of each faculty-sum of square of grand 
#mean multiply by toatl no of subject
sum_of_squarebetween=63754.7-63670.42
sum_of_squarebetween

84.27999999999884

In [26]:
#Now its very easy to calculate total sum of square of whole sample 
sum_of_squaretotal=sum_of_squarewithin+sum_of_squarebetween
sum_of_squaretotal

776.5800000000017

In [ ]:
#So in this way we have calculated sum of square total(SST)

In [27]:
#It can also be calculate using python
import statsmodels.api as sm
import numpy as np

In [ ]:
#now we have to define response variable x and y

In [28]:
y=df['score']
y

0    76
1    86
2    78
3    90
4    87
5    86
6    65
7    90
8    99
Name: score, dtype: int64

In [39]:
x=df[['faculty']]
x

faculty
0        1
1        1
2        1
3        2
4        2
5        2
6        3
7        3
8        3

In [40]:
x=sm.add_constant(x)
x

const  faculty
0    1.0        1
1    1.0        1
2    1.0        1
3    1.0        2
4    1.0        2
5    1.0        2
6    1.0        3
7    1.0        3
8    1.0        3

In [41]:
model=sm.OLS(y,x).fit() #Now we have fit linear regressor model as variable x and y.

In [43]:
sse=np.sum(model.fittedvalues-df.score)**2
sse
#this is sum of squareerror is the sum of squared difference between predicteddata point and observed data points.

3.4129278203481855e-26

In [48]:
ssr=np.sum(model.fittedvalues-df.score.mean())**2
ssr
#this sum of square regression is the sum of of differences between predicted values and mean of dependent variable.

4.543838814073028e-26

In [49]:
sst=ssr+sse
sst #This is the sum of square total as we have calculated above manually

7.956766634421213e-26

# Que no 5

In [ ]:
#first of all we have to create a dataframe using pandas.

In [1]:
import numpy as np
import pandas as pd

In [39]:
df2=pd.DataFrame({'age':np.repeat(['teenager','adult'],15),'economic_condition':np.tile(np.repeat(['low','med','high'],
                                                                                                 5),2),
                 'height_in_cm':[145,154,150,156,174,165,166,170,173,169,178,175,177,172,179,169,170,171,168,176,183,187,
                                188,189,184,183,192,195,196,187]})

In [50]:
df2


age economic_condition  height_in_cm
0   teenager                low           145
1   teenager                low           154
2   teenager                low           150
3   teenager                low           156
4   teenager                low           174
5   teenager                med           165
6   teenager                med           166
7   teenager                med           170
8   teenager                med           173
9   teenager                med           169
10  teenager               high           178
11  teenager               high           175
12  teenager               high           177
13  teenager               high           172
14  teenager               high           179
15     adult                low           169
16     adult                low           170
17     adult                low           171
18     adult                low           168
19     adult                low           176
20     adult                med           183
21     adult                med           187
22     adult                med           188
23     adult                med           189
24     adult                med           184
25     adult               high           183
26     adult               high           192
27     adult               high           195
28     adult               high           196
29     adult               high           187

In [44]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [51]:
model=ols('height_in_cm ~ C(age) + C(economic_condition) + C(age):C(economic_condition)', data=df2).fit()

In [53]:
result=sm.stats.anova_lm(model,type=2)

In [54]:
result

df       sum_sq      mean_sq          F  \
C(age)                         1.0  1840.833333  1840.833333  59.413663   
C(economic_condition)          2.0  2129.400000  1064.700000  34.363636   
C(age):C(economic_condition)   2.0    14.466667     7.233333   0.233459   
Residual                      24.0   743.600000    30.983333        NaN   

                                    PR(>F)  
C(age)                        6.055551e-08  
C(economic_condition)         9.037432e-08  
C(age):C(economic_condition)  7.935673e-01  
Residual                               NaN

In [ ]:
#Since p_value of age and economic condition are less than significant value that is 0.05 so both facors statistically
#may have any significant effect on height of person

In [ ]:
#Also pvalue for interaction effect is also greater than significance value 0.05 which tells that there is no significant 
#interaction effect between age and economic condition of person on their height according to data.

# Queno 6

In [ ]:
#ItS very simple since p value 0.02 which is less than 0.05 significant value. 

In [ ]:
#We have to accept alternate hypotheses and conclude that there exists some difference among different groups.

# Queno 7

In [ ]:
#Most effective ways to handle missing data is multiple imputation(MI). 

In [ ]:
#In ANOVA using MI wecan create multiple plausible replacements of missing data.

In [ ]:
#First missing data have to be imputed multiple times.

In [ ]:
#After that imputed datasetshave to be analyzed separately.

In [ ]:
#Then parameter estimates and hypotheses tests are done to form final set of estimates and inferences.

In [ ]:
#Using different methods in handling missing data in anova test can lead to lack of quality of ANOVA test which is done
#with that sample.

# Queno 8

# Post Hoc Test

In [ ]:
#Post Hoc test compare the differences between means with various factors to identify significant differences.

In [ ]:
#The most common post hoc test used in ANOVA are LSD(Fisher;s least significant difference),HSD(Honestly significant
# Difference test) is a single step multiple comparison procedure and SCHEFFE'S test.

In [ ]:
#These test are used to find mean that are significantly different from each other in case of alternate
#hypotheses.

In [ ]:
#In LSD test absolute mean difference of different groups is compared with t statistic of sample.

In [ ]:
#If absolute mean differencevalue is greater thantest statistic then we can conclude there is statistically 
#significant difference between group and hence we can compare various two groups with this technique.

In [ ]:
#So in this way post hoc test is used in case of alternate hypotheses to test  different group mean that are different from 
#each other.

# Example

In [ ]:
#Scenario or condition is same as given in queno 6 if p value is less than alpha or in case of alternate hypotheses.

In [ ]:
#This gives way to use post hoc test after ANOVA. 

# Que no 9

In [ ]:
#First of all we have to create three group A,B and C diet for 50 person.

In [1]:
import numpy as np
from scipy.stats import f_oneway

In [3]:
dietA=np.random.normal(loc=15,scale=6,size=50)
dietA

array([16.77304831, 21.70103905, 28.73177691, 15.02855995, 13.17716758,
        7.13162471, 20.52220966, 22.64678489, 15.97370789,  9.6670093 ,
       18.49029216, 23.89084683, 26.29900399, 16.01849944, 19.13445542,
       13.55999441, 12.40123419, 13.05979276, 23.39079667, 14.9942368 ,
       12.96801979, 17.16557099, 13.78675242, 19.15533494, 26.09789365,
       21.7046266 ,  9.72918693, 15.70481304,  9.63122077, 16.09994673,
       28.4504625 , 17.47931846, 12.8977107 , 15.12972107, 10.72586151,
       23.74962948, 11.91823305, 17.3006453 , 13.57146214, 22.05160271,
       20.14711673, 13.82379125, 21.46168539, 19.72250957, 12.47194112,
        5.98013831, 20.25221096, 22.08588509, 15.65893722, 10.67648885])

In [4]:
dietB=np.random.normal(loc=15,scale=5,size=50)
dietB

array([ 6.20964221, 20.30786787, 21.87927739, 17.72709606, 17.78893502,
       19.18105066, 14.40885198,  6.05305929, 13.83800743, 11.90482278,
       16.24920648,  9.37805629,  8.60097559, 15.25387403, 19.06046137,
        8.52132395, 19.34700052,  7.53364443, 11.37502979, 18.19347776,
       11.54310803, 14.71269684, 12.67045891,  7.6650182 , 22.40056756,
       10.24077641, 10.13453211, 13.09785583, 17.27576666, 24.23072163,
       24.98610009, 21.17137553, 20.01075738,  8.41005703, 14.20811319,
       22.57307708, 13.52875595, 20.68017808, 11.53162915, 19.94944169,
       12.15180689, 12.06758079, 18.83132915, 15.54127819, 16.19534456,
       22.46912559, 11.90940325, 14.37806271, 19.63696204, 16.43058875])

In [5]:
dietC=np.random.normal(loc=15,scale=4,size=50)
dietC

array([ 8.44979282, 12.664715  , 12.54446149, 10.60065098, 15.59822739,
       14.24434986, 21.06388092, 13.20361343, 11.62721731, 18.74955707,
       20.02729408, 11.33400205, 10.00408094,  7.38465539, 18.441563  ,
       10.23500524,  7.00531568, 14.67671962,  5.43224669, 15.97083893,
       18.25104737, 17.20366848, 16.80639883, 13.92817604, 15.49684948,
       11.9690419 , 19.54886325, 15.67998095, 12.37186894, 11.02466713,
       15.30668974, 15.68180141, 10.29531724, 16.46110563, 13.30358631,
       12.23904384, 17.1639488 , 13.68835947, 12.02315004, 17.6774459 ,
       15.92531541, 17.4754918 , 14.44405874, 15.93005518, 16.21571112,
       16.97984395, 16.7446919 , 16.91499314, 17.99194717, 13.57313354])

In [ ]:
#So we have create three group of dietA,dietB,dietC of same mean that is 15.

In [8]:
RESULT=f_oneway(dietA,dietB,dietC)
RESULT

F_onewayResult(statistic=4.110061178505604, pvalue=0.018329242948328404)

In [ ]:
#SO we get f statistic of 4.11 and p value 0.01 which is less than 0.05 and it is a case of alternate hypotheses.
#In this way we can coclude that there exists some difference between three diet mean weight loss.However according to 
#sample their mean is same but after testing we concluded that there exists some difference between mean of three diet A,B
# and C.

# Queno 10

In [1]:
import numpy as np
import pandas as pd

In [8]:
df3=pd.DataFrame({'Programme':np.repeat(['A','B','C'],10),'Experience_level':np.repeat(['Fast','Medium','Slow'],10),
                 'Timetaken_by_employee_in_hrs':[1,3,2,2.5,1.5,0.5,1.2,2.2,2.4,3.2,3.5,3.6,4,4.1,3.3,3.1,4.5,3.4,3,2.9,
                                                4.5,4.6,4.9,5,5.5,5.6,6,6.7,6.9,6.4]})

In [9]:
df3 #so here we have created dataframe for 30 employees working for three programme A,B and C and time taken by them
#for completing their work so with hese sample we have to find significant effect and interaction effect between 
#softweare programme and experience level.

Programme Experience_level  Timetaken_by_employee_in_hrs
0          A             Fast                           1.0
1          A             Fast                           3.0
2          A             Fast                           2.0
3          A             Fast                           2.5
4          A             Fast                           1.5
5          A             Fast                           0.5
6          A             Fast                           1.2
7          A             Fast                           2.2
8          A             Fast                           2.4
9          A             Fast                           3.2
10         B           Medium                           3.5
11         B           Medium                           3.6
12         B           Medium                           4.0
13         B           Medium                           4.1
14         B           Medium                           3.3
15         B           Medium                           3.1
16         B           Medium                           4.5
17         B           Medium                           3.4
18         B           Medium                           3.0
19         B           Medium                           2.9
20         C             Slow                           4.5
21         C             Slow                           4.6
22         C             Slow                           4.9
23         C             Slow                           5.0
24         C             Slow                           5.5
25         C             Slow                           5.6
26         C             Slow                           6.0
27         C             Slow                           6.7
28         C             Slow                           6.9
29         C             Slow                           6.4

In [10]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [5]:
model=ols('Timetaken_by_employee_in_hrs~C(Programme)+C(Experience_level)+C(Programme):C(Experience_level)',data=df3).fit()

In [11]:
result=sm.stats.anova_lm(model,type=2)

In [12]:
result

df     sum_sq    mean_sq          F  \
C(Programme)                       2.0  67.362000  33.681000  56.141931   
C(Experience_level)                2.0   1.970531   0.985265   1.642312   
C(Programme):C(Experience_level)   4.0   3.115946   0.778987   1.298471   
Residual                          27.0  16.198000   0.599926        NaN   

                                        PR(>F)  
C(Programme)                      2.402979e-10  
C(Experience_level)               2.122811e-01  
C(Programme):C(Experience_level)  2.955428e-01  
Residual                                   NaN

In [ ]:
#So p value of software programme is less than 0.05 which means that type of software programme have significant effect 
#on timing of work done. 
#after converting we got p value for software programme is 0.00000000024
#p value for experience level is 0.212
#p value for interaction effect between programme and experience level is 0.295.

In [ ]:
#While p value of experience level is more than 0.05 which meams there is not any significant effect of experience level
#on work being done.

In [ ]:
#Also p value for interaction effect is also greater than significance value that is 0.05 which means there is not significa
#nt interaction between software programme and experience level.


# Queno 11

In [ ]:
#First of all we have to create two sample of 100 students score of traditional teaching meathod and new teaching method.

In [1]:
import numpy as np

In [3]:
traditional_teaching_method=np.random.normal(loc=70,scale=10,size=100)
traditional_teaching_method #score of students who are conducting traditional teaching method

array([70.49116526, 63.24509589, 74.82710345, 86.98630546, 73.83934898,
       78.28491327, 73.62096753, 93.35304529, 69.29672984, 85.50373728,
       72.41305897, 46.58467339, 72.89468346, 64.4760733 , 59.5511576 ,
       72.10489773, 69.77828178, 72.90097168, 68.41705252, 65.72517113,
       67.79681728, 56.55953124, 51.29091356, 86.15394605, 82.32384729,
       82.01728972, 72.1158764 , 67.6892383 , 62.50809984, 75.03525308,
       67.53076683, 61.51024586, 53.59931817, 75.51886341, 62.01046092,
       67.69948764, 57.57950597, 62.16879818, 81.70491807, 70.24040649,
       58.13084493, 80.31704074, 74.86423794, 67.67699354, 80.65769971,
       72.83095084, 66.08910147, 78.26917684, 67.28038561, 78.45285058,
       62.33212996, 63.33920913, 68.98559436, 63.91450803, 87.5636434 ,
       59.66574862, 73.17336023, 64.42216052, 63.5459828 , 76.47356459,
       62.39078535, 68.51361452, 75.69569519, 79.20587079, 68.11176061,
       75.36341185, 73.4342612 , 63.3801095 , 81.75600714, 58.27

In [4]:
new_teaching_method=np.random.normal(loc=94,scale=10,size=100)
new_teaching_method

array([ 91.29524341,  97.77387799,  85.94357826, 104.46198782,
       100.8153688 ,  92.68627845,  97.02349256,  72.23322333,
        88.22386951,  89.91030945,  96.94632536,  83.69195464,
        92.95243543,  82.99500431,  87.58284161,  98.78223562,
        93.94663939,  96.74982854,  90.56977395,  91.02026774,
        80.65936254, 102.35684532, 103.00686521,  87.71343114,
        78.75060265,  90.00918047,  81.85471758, 103.94525265,
       109.67629014,  93.30595898,  79.18984561,  74.96499153,
       108.60849824, 107.74163461,  86.84304643,  98.29408488,
        81.59330158, 102.07194721, 109.7686973 ,  87.48975111,
        84.12818778,  93.97957746, 100.36144753, 105.43616814,
        99.54083748, 101.28348308,  93.73438801, 103.76071311,
       108.9139156 ,  79.30880173,  82.55500799, 108.02056665,
        90.63928579, 100.21600794,  75.6674318 ,  92.49743476,
        93.65128279,  97.8248985 ,  92.18604729, 111.66744323,
        92.57463222,  90.41323891,  97.01535591,  95.92

In [6]:
#Now conduct two sample t test
import scipy.stats as stats
import pingouin as pg

In [12]:
result=pg.ttest(traditional_teaching_method,new_teaching_method,correction=True)
result

T         dof alternative         p-val            CI95%  \
T-test -18.372922  197.959394   two-sided  1.182420e-44  [-27.1, -21.85]   

         cohen-d       BF10  power  
T-test  2.598324  1.109e+41    1.0

In [ ]:
#So p value is 0.000000000000018 which is very much less than 0.05 which states that score obtained by mew teaching method
#is very much different from score obtained by new teaching method.

In [3]:
#Now we can conduct post  hoc tukey test for this we have to cretae dataframe
import numpy as np
import pandas as pd

In [4]:
df4=pd.DataFrame({'SCORE':[70.49116526, 63.24509589, 74.82710345, 86.98630546, 73.83934898,
       78.28491327, 73.62096753, 93.35304529, 69.29672984, 85.50373728,
       72.41305897, 46.58467339, 72.89468346, 64.4760733 , 59.5511576 ,
       72.10489773, 69.77828178, 72.90097168, 68.41705252, 65.72517113,
       67.79681728, 56.55953124, 51.29091356, 86.15394605, 82.32384729,
       82.01728972, 72.1158764 , 67.6892383 , 62.50809984, 75.03525308,
       67.53076683, 61.51024586, 53.59931817, 75.51886341, 62.01046092,
       67.69948764, 57.57950597, 62.16879818, 81.70491807, 70.24040649,
       58.13084493, 80.31704074, 74.86423794, 67.67699354, 80.65769971,
       72.83095084, 66.08910147, 78.26917684, 67.28038561, 78.45285058,
       62.33212996, 63.33920913, 68.98559436, 63.91450803, 87.5636434 ,
       59.66574862, 73.17336023, 64.42216052, 63.5459828 , 76.47356459,
       62.39078535, 68.51361452, 75.69569519, 79.20587079, 68.11176061,
       75.36341185, 73.4342612 , 63.3801095 , 81.75600714, 58.27059916,
       50.08923763, 83.22398962, 62.52793675, 52.23426066, 71.81139301,
       58.55439654, 81.28428166, 71.84686483, 70.59035174, 69.17312058,
       69.97491867, 70.33066776, 61.6358341 , 72.71270374, 57.73659719,
       44.20247276, 73.59895341, 72.48430346, 63.8291502 , 64.52133129,
       69.27315887, 56.18628465, 77.69748803, 77.46355912, 65.26007489,
       56.71376229, 53.63701882, 75.27279904, 81.56888218, 79.79240116,91.29524341,  97.77387799,  85.94357826, 104.46198782,
       100.8153688 ,  92.68627845,  97.02349256,  72.23322333,
        88.22386951,  89.91030945,  96.94632536,  83.69195464,
        92.95243543,  82.99500431,  87.58284161,  98.78223562,
        93.94663939,  96.74982854,  90.56977395,  91.02026774,
        80.65936254, 102.35684532, 103.00686521,  87.71343114,
        78.75060265,  90.00918047,  81.85471758, 103.94525265,
       109.67629014,  93.30595898,  79.18984561,  74.96499153,
       108.60849824, 107.74163461,  86.84304643,  98.29408488,
        81.59330158, 102.07194721, 109.7686973 ,  87.48975111,
        84.12818778,  93.97957746, 100.36144753, 105.43616814,
        99.54083748, 101.28348308,  93.73438801, 103.76071311,
       108.9139156 ,  79.30880173,  82.55500799, 108.02056665,
        90.63928579, 100.21600794,  75.6674318 ,  92.49743476,
        93.65128279,  97.8248985 ,  92.18604729, 111.66744323,
        92.57463222,  90.41323891,  97.01535591,  95.9226384 ,
        97.61439856, 107.69860394,  87.86859557,  90.70778624,
        87.75422827,  80.02785882,  91.77930917,  97.98098673,
        95.59430019,  87.91940082, 105.23043293,  88.16683279,
        90.71804944, 108.45793296,  89.89281195, 101.91016317,
        99.44237381,  95.67922825,  99.50436128,  95.09211527,
        80.68778331,  83.1280927 , 110.59244172, 101.10131522,
       102.81535319,  95.39858888,  78.37365934, 100.04769481,
        96.32675624,  90.216931  ,  96.40327111,  96.54925264,
        96.14296708,  86.60692713,  99.34427886,  66.50534512],'group':np.repeat(['traditional teaching method',
                                                                                 'new teaching method'],repeats=100)})

In [5]:
df4

SCORE                        group
0    70.491165  traditional teaching method
1    63.245096  traditional teaching method
2    74.827103  traditional teaching method
3    86.986305  traditional teaching method
4    73.839349  traditional teaching method
..         ...                          ...
195  96.549253          new teaching method
196  96.142967          new teaching method
197  86.606927          new teaching method
198  99.344279          new teaching method
199  66.505345          new teaching method

[200 rows x 2 columns]

In [7]:
#now we can conduct tukey test
from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [9]:
tukey=pairwise_tukeyhsd(endog=df4['SCORE'],groups=df4['group'],alpha=0.05)

In [10]:
tukey

In [11]:
print(tukey)

                  Multiple Comparison of Means - Tukey HSD, FWER=0.05                  
       group1                  group2           meandiff p-adj  lower    upper   reject
---------------------------------------------------------------------------------------
new teaching method traditional teaching method -24.4734   0.0 -27.1002 -21.8466   True
---------------------------------------------------------------------------------------


In [ ]:
#As p value for difference in mean between traditional and new teaching method is 0 which means that there is statistically 
#significant difference between means of new teaching and traditional teaching as p value is less than 0.05.

# Queno 12

In [ ]:
#create three group of STORE A,B and C according to their no of sale.

In [13]:
storeA=np.random.normal(loc=100,scale=10,size=30)
storeA

array([107.96088523, 110.09768376, 102.38845638,  86.05780226,
       106.23710791, 105.03842777, 102.3977176 , 102.78857939,
        91.78047734, 101.96710099,  99.53625279,  94.33330231,
       120.77619951,  83.68468328, 119.48326782, 102.90568063,
       101.10586026,  97.65909797,  92.50894139,  98.59179601,
       119.79648631, 107.88956518,  98.73091027,  92.20655846,
        92.31596443, 115.74374724,  83.23156595,  85.39179913,
       103.19229802,  94.11109848])

In [14]:
storeB=np.random.normal(loc=90,scale=10,size=30)
storeB

array([ 75.39450021,  87.88672748,  95.87649   ,  84.11048336,
       100.60768488,  77.71501442,  74.90541631,  98.76026472,
        83.2150574 ,  98.31666104,  71.5921787 ,  87.47946965,
        96.14427835, 106.06207911,  99.03099057,  85.21743908,
        93.86197759,  81.54424511,  67.39332457,  87.62555279,
        95.72661999,  81.21438975,  92.83373233,  97.7284351 ,
        84.28650382,  69.78802376,  94.6637884 ,  71.26504849,
        70.80057324,  80.09789532])

In [15]:
storeC=np.random.normal(loc=80,scale=10,size=30)
storeC

array([ 88.87848105,  87.44418851,  67.17333428,  95.81457207,
        94.09475739,  73.59673231,  87.69730469,  94.16572869,
        49.66976029,  88.0292543 ,  82.2461809 ,  81.02982356,
        73.21792341,  81.32616222,  89.91285846,  84.21935795,
        76.65066523,  81.35766542,  85.43030806,  77.24134061,
        76.65436397,  73.50024728, 104.4044532 ,  79.55534432,
        85.60992922,  68.5942724 ,  78.14018138,  81.74468709,
        57.15923537,  77.9507711 ])

In [18]:
#NOW we have to create dataframe
df5=pd.DataFrame({'No_of_days':np.repeat([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,
                                         29,30],3),'store':np.tile(['A','B','C'],30),'No_of_sales':[107, 110, 102,86,106, 105, 102 , 102,
        91,101,99,94,120,83,119,102,101,97,92,98,119,107,98,92,92,115,83,85,103,94,75,87,95,84,100,77,74,98,83,98,71, 87,
        96,106,99,85,93,81,67,87,95,81,92,97,84,69,94,71,70,80,88,87,67,95,94,73,87,94,49,88,82,81,73,81,89,84,76,81,85,77,
        76,73,104,79,85,68,78,84,57,77]})

In [19]:
df5

No_of_days store  No_of_sales
0            1     A          107
1            1     B          110
2            1     C          102
3            2     A           86
4            2     B          106
..         ...   ...          ...
85          29     B           68
86          29     C           78
87          30     A           84
88          30     B           57
89          30     C           77

[90 rows x 3 columns]

In [21]:
from statsmodels.stats.anova import AnovaRM
#for testing repeated measures in ANOVA.

In [26]:
RESULT=AnovaRM(data=df5,depvar='No_of_sales',subject='store',within=['No_of_days']).fit()

In [27]:
print(RESULT)

                  Anova
           F Value  Num DF  Den DF Pr > F
-----------------------------------------
No_of_days  2.1913 29.0000 58.0000 0.0056



In [ ]:
#hence p value is less than 0.05 which is 0.0056 in favour of alternate hypotheses for which we can conclude that there is 
#statistically difference among the sale of store A,B and C.

In [ ]:
#now we can conduct post hoc test to see which store differ from each other for this we have to create new dataframe

In [29]:
df6=pd.DataFrame({'no_of_sales':[107, 110, 102,86,106, 105, 102 , 102,
        91,101,99,94,120,83,119,102,101,97,92,98,119,107,98,92,92,115,83,85,103,94,75,87,95,84,100,77,74,98,83,98,71, 87,
        96,106,99,85,93,81,67,87,95,81,92,97,84,69,94,71,70,80,88,87,67,95,94,73,87,94,49,88,82,81,73,81,89,84,76,81,85,77,
        76,73,104,79,85,68,78,84,57,77],'group':np.repeat(['storeA','storeB','storeC'],repeats=30)})

In [30]:
df6

no_of_sales   group
0           107  storeA
1           110  storeA
2           102  storeA
3            86  storeA
4           106  storeA
..          ...     ...
85           68  storeC
86           78  storeC
87           84  storeC
88           57  storeC
89           77  storeC

[90 rows x 2 columns]

In [32]:
tukey=pairwise_tukeyhsd(endog=df6['no_of_sales'],groups=df6['group'],alpha=0.05)


In [33]:
print(tukey)

 Multiple Comparison of Means - Tukey HSD, FWER=0.05 
group1 group2 meandiff p-adj  lower    upper   reject
-----------------------------------------------------
storeA storeB    -14.3   0.0  -20.893   -7.707   True
storeA storeC -19.7667   0.0 -26.3597 -13.1736   True
storeB storeC  -5.4667 0.124 -12.0597   1.1264  False
-----------------------------------------------------


In [ ]:
#Thus according to post hoc test only sales of store B and C statistically do not differ as its p value is greater than 
#alpha 0.05.