# Queno 1

In [3]:
import numpy as np
import scipy.stats as stats
group1=np.array([20,25,50,65,76,87]) #create two group array
group1

array([20, 25, 50, 65, 76, 87])

In [4]:
group2=np.array([89,90,56,76,87,34])
group2

array([89, 90, 56, 76, 87, 34])

In [6]:
variance1=np.var(group1,ddof=1) #calculating variance of two group with deltas of freedom 1 
variance1

741.3666666666666

In [8]:
variance2=np.var(group2,ddof=1)
variance2

510.8

In [9]:
f_value=variance1/variance2
f_value #f statistic value is 1.45

1.4513834507961365

In [10]:
df1=len(group1)-1  #df1 and df2 isdegrees of freedom for group1 and group 2
df1

5

In [11]:
df2=len(group2)-1
df2

5

In [12]:
p_value=stats.f.cdf(f_value,df1,df2)
p_value #this p value

0.653661794984314

In [ ]:
#hence we got p value 0.653 and f statistic 1.45 by variance ratio test.

# Que no 2

In [14]:
result=stats.f.ppf(q=1-.05,dfn=6,dfd=9) #dfn is degrees offreedom in numerator
                                        #dfd is degrees of freedom in denominator
                                         #q=1-alpha

In [16]:
print('critical f value:',result) #below is critical f value

critical f value: 3.373753647039214


# Queno 3

In [1]:
import math
from random import gauss

In [11]:
mean=10
variance=8
sample1=[gauss(10,math.sqrt(7)) for i in range(50)]
sample1 #so we have create sample with known variance 7 and mean 10

[7.6594369832899245,
 7.791536017251296,
 13.277019000021502,
 11.981702266618933,
 8.15531734078187,
 8.848054294881083,
 10.40112124947844,
 5.604451368416479,
 11.154972160683858,
 9.126957347471214,
 4.217625432249498,
 8.805818543542113,
 9.813289880890254,
 6.953598841444576,
 8.501194411282105,
 9.850738837921192,
 7.933624106361728,
 5.341589002940519,
 5.3432067659203035,
 12.528548633616808,
 7.567523001553387,
 12.096245870190366,
 11.545964647301574,
 11.10470257693388,
 4.683161358213315,
 10.846486499499209,
 6.497043096854724,
 10.876693232605572,
 11.574569164024204,
 12.790522753278056,
 12.89070037119927,
 11.357068252665234,
 6.903971956900376,
 7.2192097674374995,
 13.088431673256206,
 8.195287068674501,
 7.113592514429028,
 15.253203126519308,
 11.060361960636302,
 14.051401367450552,
 9.335074414253814,
 10.377000651618113,
 8.80811196519239,
 9.411284074170181,
 10.48629353356618,
 9.80125995087294,
 11.962965178408977,
 8.988405106570125,
 6.074909010628893,
 7.

In [12]:
var1=np.var(sample1)
var1#so its variance is near to 7

6.555791014475627

In [8]:
sample2=[gauss(15,math.sqrt(8)) for i in range(50)]
sample2

[10.191403216408197,
 19.088829809573284,
 15.762644478936668,
 18.11299682298109,
 12.448629715775427,
 10.656293722569078,
 12.35755472777183,
 17.94601890923353,
 15.713108138771723,
 11.68820440425388,
 22.935697679027662,
 15.667271798814715,
 9.726936399028297,
 17.192470124049905,
 10.689646150109745,
 15.546243328661259,
 13.767613399265986,
 10.91955508666884,
 16.48898950739425,
 15.542506565936709,
 12.731744455631965,
 14.210128622452807,
 13.093790247981698,
 14.070901153722433,
 19.819945990823882,
 17.288634491088043,
 17.868946608421275,
 13.813627840769943,
 12.57966518137285,
 15.877955478770627,
 16.3407418363799,
 13.27889889671443,
 16.42873541664153,
 18.411611321448255,
 19.796702214651816,
 16.301630572950277,
 20.223720036280113,
 15.762686447130326,
 16.879084356787928,
 18.443386216158014,
 11.90794592665385,
 21.37084886704943,
 16.83225792711555,
 13.41633991273678,
 10.01036564982595,
 17.308523112366778,
 15.151522142160793,
 15.275312154999707,
 14.11377

In [9]:
var2=np.var(sample2)
var2#its variiance is near to 8

9.233467023943811

In [13]:
f_value=var2/var1
f_value #as variance2 is greater so we have to divide it by var1
#this is f statistic value

1.4084443820060304

In [14]:
df1=49
df2=49 #1 less than no of sample

In [15]:
p_value=stats.f.cdf(f_value,df1,df2)
p_value 
#this is p value

0.882921808580744

In [ ]:
#As p value is greater than alpha so it is a case of null hypotheses and which indicates there is not enough evidence
#to conclude that variance are significantly different so results are not statistically significant. 

# Queno 4

In [ ]:
#First of all we have to create two sample of population.

In [18]:
variance1=10
variance2=15

In [19]:
f_value=variance2/variance1
f_value

1.5

In [20]:
#now we have to find f critical value
import numpy as np
import scipy.stats as stats

In [21]:
df1=11
df2=11 #degrees of freedom

In [22]:
p_value=stats.f.cdf(f_value,df1,df2)
p_value

0.7438051006321003

In [ ]:
#hence p_value is greater than alpha so it is a case of alternate hypotheses which indicate that there is not enough
#evidence to say that variance of both sample are statistically different.

# Queno 5

In [23]:
var1=0.005
var2=0.006
f_value=var2/var1
f_value

1.2

In [24]:
df1=199 #lets assume 1st data from which sample taken is of 200 size so we take dof as 199 
df2=24 #its the dof of sample data of size 25

In [25]:
#now calculate p value
p_value=stats.f.cdf(f_value,df1,df2)
p_value

0.6915457318156911

In [ ]:
#as p value is greater than alpha 0.01 so it is a case of null hypotheses which does not have any evidence to 
#differ the variance between the data and sample from which it taken that is 25

# Queno 6

In [53]:

sample=np.linspace(3,20,10)
sample  #this is sample of no from 3 to 20 of size 10 and from this sample we have to generate f distribution
          #for two groups having 10 observation.

array([ 3.        ,  4.88888889,  6.77777778,  8.66666667, 10.55555556,
       12.44444444, 14.33333333, 16.22222222, 18.11111111, 20.        ])

In [54]:
dfn=1
dfd=9

In [55]:
from scipy.stats import f
result=f.pdf(sample,dfn,dfd)

In [56]:
result 
#hence we have created f distribution of two group having 10 observation 

array([0.05316386, 0.02005122, 0.00900141, 0.00452256, 0.00246599,
       0.00143226, 0.00087504, 0.00055733, 0.0003676 , 0.00024979])

In [57]:
result.mean() #this is the mean of f distribution

0.009268705153452485

In [58]:
np.var(result) #this is the variance of f distribution

0.0002480243363550442

# Que no 7

In [ ]:
#lets create two sample with variance 25 and 20 with size 10 and 15.

In [3]:
variance1=25
variance2=20

In [5]:
f_value=variance1/variance2
f_value

1.25

In [6]:
#now we have to calculate p_value
import scipy.stats as stats

In [7]:
df1=9
df2=14  #df1 is 9 one less than no of observation that is 9 and in the same way df2.

In [8]:
p_value=stats.f.cdf(f_value,df1,df2)

In [9]:
p_value

0.6583902808707023

In [ ]:
#hence as p_value is greater than 0.1 alpha so it is a case of null hypotheses and we can conclude that there is not enough
#evidence to tell that variances are significantly different.

# Que no 8

In [10]:
import numpy as np

In [27]:
#convert two waiting time in array oftwo restaurant
restaurantA=np.array([24,25,28,23,22,20,27])
restaurantA

array([24, 25, 28, 23, 22, 20, 27])

In [28]:
restaurantB=np.array([31,33,35,30,32,26])
restaurantB

array([31, 33, 35, 30, 32, 26])

In [29]:
#NOW CALCUALTE VARIANCE OF BOTH RESTAURANT 
varianceA=np.var(restaurantA)
varianceA

6.6938775510204085

In [30]:
varianceB=np.var(restaurantB)
varianceB

7.805555555555556

In [31]:
f_value=varianceB/varianceA
f_value #this f statistic

1.1660738482384825

In [32]:
df1=6
df2=5   #df1 is 6 one less than no of observation in the same way df2

In [34]:
p_value=stats.f.cdf(f_value,df1,df2)
p_value

0.5574494640819424

In [ ]:
#here also p value is greater than alpha 0.05 which is null hypotheses and we can conclude that there is not any evidence 
#to tell variance of both sample is statistically different. 

# Queno 9

In [35]:
#letscreate two group array of score of student
groupA=np.array([80,85,90,92,87,83])
groupA

array([80, 85, 90, 92, 87, 83])

In [36]:
groupB=np.array([75,78,82,79,81,84])
groupB

array([75, 78, 82, 79, 81, 84])

In [37]:
#now calculate variance of both group
var1=np.var(groupA,ddof=1)
var1

19.76666666666667

In [38]:
var2=np.var(groupB,ddof=1)
var2

10.166666666666666

In [39]:
f_value=var1/var2
f_value #it is f statistic

1.9442622950819677

In [40]:
df1=5
df2=5 #both have 5 degree of freedom

In [41]:
p_value=stats.f.cdf(f_value,df1,df2)

In [42]:
p_value

0.7584478225464656

In [ ]:
#Hence pvalue is greater than alpha 0.01 so it isa case of null hypotheses and we can coclude that there is not enough 
#evidence to say variance of both sample are statistically different. 