# Queno 1

In [2]:
import numpy as np
import scipy.stats as stats
group1=np.array([20,25,50,65,76,87]) #create two group array
group1

array([20, 25, 50, 65, 76, 87])

In [4]:
group2=np.array([89,90,56,76,87,34])
group2

array([89, 90, 56, 76, 87, 34])

In [6]:
variance1=np.var(group1,ddof=1) #calculating variance of two group with deltas of freedom 1 
variance1

741.3666666666666

In [8]:
variance2=np.var(group2,ddof=1)
variance2

510.8

In [9]:
f_value=variance1/variance2
f_value #f statistic value is 1.45

1.4513834507961365

In [10]:
df1=len(group1)-1  #df1 and df2 isdegrees of freedom for group1 and group 2
df1

5

In [11]:
df2=len(group2)-1
df2

5

In [12]:
p_value=stats.f.cdf(f_value,df1,df2)
p_value #this p value

0.653661794984314

In [ ]:
#hence we got p value 0.653 and f statistic 1.45 by variance ratio test.

# Que no 2

In [14]:
result=stats.f.ppf(q=1-.05,dfn=6,dfd=9) #dfn is degrees offreedom in numerator
                                        #dfd is degrees of freedom in denominator
                                         #q=1-alpha

In [16]:
print('critical f value:',result) #below is critical f value

critical f value: 3.373753647039214


# Queno 3

In [1]:
import math
from random import gauss

In [47]:
mean=10
variance=7
sample1=[gauss(10,math.sqrt(7)) for i in range(50)]
sample1 #so we have create sample with known variance 7 and mean 10

[5.733910956906093,
 11.345073380972046,
 7.1079469777450495,
 8.75642089963577,
 16.41269789680089,
 9.864988769253765,
 9.60290645862761,
 11.04636564835059,
 7.412242118207152,
 8.566005866319578,
 9.450732096196507,
 11.928257650972737,
 10.733306070153425,
 13.037990429683497,
 8.17421888281543,
 7.8614792606355195,
 10.46099307268746,
 8.73444701651419,
 10.861342158461127,
 11.797734138198718,
 15.178613007084516,
 12.157705162478818,
 8.361088414896733,
 11.300020551919458,
 15.384267082537143,
 8.718712634232961,
 7.059269014129853,
 12.829077450015234,
 5.655521274427086,
 4.42442758141944,
 15.217559575079123,
 8.646442067297777,
 9.745435027990775,
 7.700490306474789,
 11.32385762184915,
 5.933630614112908,
 9.377411903242617,
 8.498912650226092,
 10.384322852667752,
 7.622829884834909,
 10.411576650266257,
 11.480396444505867,
 10.924720897815458,
 4.893213626096908,
 7.42905458741463,
 8.58383711379194,
 6.527404324857725,
 6.2243118954944245,
 8.494460412932998,
 3.98071

In [53]:
var1=np.var(sample1)
var1#so its variance is near to 7

7.826108083192504

In [49]:
sample2=[gauss(15,math.sqrt(7)) for i in range(50)]
sample2

[21.289766036459156,
 12.230432639540235,
 16.501220119542392,
 11.97591981098811,
 16.637457571472012,
 16.014544431571334,
 10.379871479699055,
 14.75990915498408,
 13.668162290224615,
 17.736873195805366,
 13.715316270491897,
 17.404260646783104,
 15.897163719945421,
 16.450504060112657,
 15.476792316771322,
 18.161132585697565,
 14.24121949776837,
 9.746247323511476,
 17.767117304183444,
 15.677286252088095,
 20.02109398409305,
 11.815177953232869,
 10.387888783227268,
 17.535272290387805,
 15.216808984836753,
 13.891382595695912,
 16.41491552196493,
 17.827850949639917,
 16.16913522121394,
 18.419624343523434,
 15.136780746250173,
 15.322110385038956,
 15.448582567018875,
 16.026033804480537,
 16.879776285263326,
 14.36371686551116,
 11.040110761608187,
 14.433559411367701,
 13.492480537327818,
 18.706436330650494,
 15.549979101758687,
 17.44840105859807,
 14.74729680256226,
 17.84204167629183,
 8.744753352161151,
 18.27198281809483,
 14.924482699567783,
 11.720459434410037,
 14.2

In [52]:
var2=np.var(sample2)
var2#its variiance is also near to 7

7.047944598831368

In [54]:
f_value=var1/var2
f_value 
#this is f statistic value

1.1104099888200263

In [55]:
df1=49
df2=49 #1 less than no of sample

In [57]:
p_value=stats.f.cdf(f_value,df1,df2)
p_value 
#this is p value

0.6422966521692812

In [ ]:
#As p value is greater than alpha so it is a case of null hypotheses and which indicates there is not enough evidence
#to conclude that variance are significantly different so results are not statistically significant. 

# Queno 4

In [ ]:
#First of all we have to create two sample of population.

In [21]:
variance1=10
variance2=15

In [22]:
f_value=variance1/variance2
f_value

0.6666666666666666

In [23]:
#now we have to find f critical value
import numpy as np
import scipy.stats as stats

In [24]:
df1=11
df2=11 #degrees of freedom

In [25]:
p_value=stats.f.cdf(f_value,df1,df2)
p_value

0.2561948993678998

In [ ]:
#hence p_value is greater than alpha so it is a case of alternate hypotheses which indicate that there is not enough
#evidence to say that variance of both sample are statistically different.

# Queno 5

In [27]:
var1=0.005
var2=0.006
f_value=var1/var2
f_value

0.8333333333333334

In [28]:
df1=199 #lets assume 1st data from which sample taken is of 200 size so we take dof as 199 
df2=24 #its the dof of sample data of size 25

In [30]:
#now calculate p value
p_value=stats.f.cdf(f_value,df1,df2)
p_value

0.245466008826903

In [ ]:
#as p value is greater than alpha 0.01 so it is a case of null hypotheses which does not have any evidence to 
#differ the variance between the data and sample from which it taken that is 25

# Queno 6

In [53]:

sample=np.linspace(3,20,10)
sample  #this is sample of no from 3 to 20 of size 10 and from this sample we have to generate f distribution
          #for two groups having 10 observation.

array([ 3.        ,  4.88888889,  6.77777778,  8.66666667, 10.55555556,
       12.44444444, 14.33333333, 16.22222222, 18.11111111, 20.        ])

In [54]:
dfn=1
dfd=9

In [55]:
from scipy.stats import f
result=f.pdf(sample,dfn,dfd)

In [56]:
result 
#hence we have created f distribution of two group having 10 observation 

array([0.05316386, 0.02005122, 0.00900141, 0.00452256, 0.00246599,
       0.00143226, 0.00087504, 0.00055733, 0.0003676 , 0.00024979])

In [57]:
result.mean() #this is the mean of f distribution

0.009268705153452485

In [58]:
np.var(result) #this is the variance of f distribution

0.0002480243363550442

# Que no 7

In [ ]:
#lets create two sample with variance 25 and 20 with size 10 and 15.

In [3]:
variance1=25
variance2=20

In [5]:
f_value=variance1/variance2
f_value

1.25

In [6]:
#now we have to calculate p_value
import scipy.stats as stats

In [7]:
df1=9
df2=14  #df1 is 9 one less than no of observation that is 9 and in the same way df2.

In [8]:
p_value=stats.f.cdf(f_value,df1,df2)

In [9]:
p_value

0.6583902808707023

In [ ]:
#hence as p_value is greater than 0.1 alpha so it is a case of null hypotheses and we can conclude that there is not enough
#evidence to tell that variances are significantly different.

# Que no 8

In [10]:
import numpy as np

In [12]:
#convert two waiting time in array oftwo restaurant
restaurantA=np.array([24,25,28,23,22,20,27])
restaurantA

array([24, 25, 28, 23, 22, 20, 27])

In [13]:
restaurantB=np.array([31,33,35,30,32,26])
restaurantB

array([31, 33, 35, 30, 32, 26])

In [14]:
#NOW CALCUALTE VARIANCE OF BOTH RESTAURANT 
varianceA=np.var(restaurantA)
varianceA

6.6938775510204085

In [15]:
varianceB=np.var(restaurantB)
varianceB

7.805555555555556

In [16]:
f_value=varianceA/varianceB
f_value #this f statistic

0.8575786186360665

In [17]:
df1=6
df2=5   #df1 is 6 one less than no of observation in the same way df2

In [18]:
p_value=stats.f.cdf(f_value,df1,df2)
p_value

0.42142186320509295

In [ ]:
#here also p value is greater than alpha 0.05 which is null hypotheses and we can conclude that there is not any evidence 
#to tell variance of both sample is statistically different. 

# Queno 9

In [19]:
#letscreate two group array of score of student
groupA=np.array([80,85,90,92,87,83])
groupA

array([80, 85, 90, 92, 87, 83])

In [20]:
groupB=np.array([75,78,82,79,81,84])
groupB

array([75, 78, 82, 79, 81, 84])

In [31]:
#now calculate variance of both group
var1=np.var(groupA,ddof=1)
var1

19.76666666666667

In [34]:
var2=np.var(groupB,ddof=1)
var2

10.166666666666666

In [35]:
f_value=var1/var2
f_value #it is f statistic

1.9442622950819677

In [36]:
df1=5
df2=5 #both have 5 degree of freedom

In [37]:
p_value=stats.f.cdf(f_value,df1,df2)

In [38]:
p_value

0.7584478225464656

In [ ]:
#hence p_value is greater than alpha 0.01 so it is a case of null hypotheses and we can conclude that variance of both group
#are not statistically different. 